# Generated by Django 5.1.3 on 2025-04-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(default=' ', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Drink_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(max_length=20)),
                ('house', models.CharField(choices=[('M', 'House of Miczek'), ('Z', 'Hosuse of Zegar Tadeusz'), ('S', 'House of Zegar Stanisław'), ('K', 'House of Krakowski'), ('H', 'Houseless')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.ManyToManyField(to='api.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('TP', 'odbyło się'), ('PO', 'przełożone'), ('PL', 'zaplanowane')], default='PL', max_length=2)),
                ('host', models.CharField(choices=[('M', 'W domu nr 17f'), ('Z', 'W domu nr 17'), ('S', 'W domu nr 17a'), ('K', 'W domu nr 136a')], max_length=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drink')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guest')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
    ]
