# Generated by Django 5.0.6 on 2024-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('satus', models.CharField(choices=[('TP', 'odbyło się'), ('PO', 'przełożone'), ('PL', 'zaplanowane')], default='PL', max_length=2)),
                ('host', models.CharField(choices=[('M', 'W domu nr 17f'), ('Z', 'W domu nr 17'), ('S', 'W domu nr 17a'), ('K', 'W domu nr 136a')], default='Z', max_length=1)),
            ],
        ),
    ]
