# Generated by Django 5.0.6 on 2024-07-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='satus',
            new_name='status',
        ),
    ]
