# Generated by Django 5.0.6 on 2024-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_satus_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.CharField(choices=[('M', 'W domu nr 17f'), ('Z', 'W domu nr 17'), ('S', 'W domu nr 17a'), ('K', 'W domu nr 136a')], max_length=1),
        ),
    ]
