# Generated by Django 5.0.6 on 2024-07-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meeting_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='event_date',
        ),
    ]
