# Generated by Django 5.0.6 on 2024-07-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_drink_guest_menu_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Drink_images/'),
        ),
    ]
