# Generated by Django 5.0.6 on 2024-07-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
        ),
    ]
