# Generated by Django 5.0.6 on 2024-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meeting_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
